export const SEGMENTS = [
  "Advocacia",
  "Agropecuária",
  "Arquitetura e Urbanismo",
  "Bancos e Financeiras",
  "Beleza e Estética",
  "Blogs e Sites Pessoais",
  "Clínicas e Saúde",
  "Comércio Varejista",
  "Concessionárias de Veículos",
  "Construção Civil",
  "Contabilidade",
  "Demolição e Terraplanagem",
  "Distribuidoras e Atacadistas",
  "E-commerce",
  "Educação e Ensino",
  "Engenharia",
  "Esportes e Fitness",
  "Esoterismo",
  "Eventos e Entretenimento",
  "Farmácias e Drogarias",
  "Fotografia",
  "Gráficas e Comunicação Visual",
  "Hotelaria e Turismo",
  "Imobiliárias",
  "Indústria",
  "Informática e Tecnologia",
  "Logística e Transportes",
  "Marketing e Publicidade",
  "Mecânicas e Autopeças",
  "Mineração",
  "Moda e Vestuário",
  "Pet Shops e Veterinárias",
  "Restaurantes e Alimentação",
  "Serviços Domésticos",
  "Serviços Financeiros",
  "Serviços Gerais",
  "Supermercados e Mercados",
  "Telecomunicações",
  "Terceiro Setor"
];

export const COUNTRIES = [
  { code: "BR", name: "Brasil" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "US", name: "Estados Unidos" },
  { code: "PT", name: "Portugal" },
  { code: "UY", name: "Uruguai" }
];
