"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { ImagePlus, LayoutTemplate, Menu, Pencil, Plus, Save, Settings, Trash2 } from "lucide-react";
import { AdminFetchError, adminFetch } from "@/lib/adminAuth";
import { RichTextEditor, RichTextPreview } from "@/components/RichTextEditor";
import { Logo } from "@/components/brand/Logo";

type Section = { id:string; page_id:string; section_key:string; section_type:string; title?:string; subtitle?:string; body?:string; image_url?:string; button_label?:string; button_href?:string; sort_order:number; visible:boolean };
type Page = { id:string; slug:string; title:string; subtitle?:string; page_type:string; status:"draft"|"published"|"hidden"; seo_title?:string; seo_description?:string; nodere_cms_sections?:Section[] };
type Nav = { id:string; location:"header"|"footer"|"app"; label:string; href:string; sort_order:number; visible:boolean };
type Plan = { id:string; plan:string; seats_limit:number; credits_limit:number; modules:string[]; features:Record<string,unknown> };
type PageForm = { slug:string; title:string; subtitle:string; pageType:string; status:Page["status"]; seoTitle:string; seoDescription:string };
const blankPage:PageForm={slug:"",title:"",subtitle:"",pageType:"institutional",status:"draft",seoTitle:"",seoDescription:""};
const blankSection={pageId:"",sectionKey:"",sectionType:"content",title:"",subtitle:"",body:"",imageUrl:"",buttonLabel:"",buttonHref:"",sortOrder:0,visible:true};

export function ContentAdminClient(){
 const searchParams=useSearchParams();
 const initialArea=searchParams.get("area");
 const [area,setArea]=useState<"pages"|"navigation"|"plans">(initialArea==="navigation"||initialArea==="plans"?initialArea:"pages"),[pages,setPages]=useState<Page[]>([]),[navigation,setNavigation]=useState<Nav[]>([]),[plans,setPlans]=useState<Plan[]>([]);
 const [pageForm,setPageForm]=useState({...blankPage}),[sectionForm,setSectionForm]=useState({...blankSection}),[navForm,setNavForm]=useState({location:"header" as Nav["location"],label:"",href:"",sortOrder:0,visible:true});
 const [editingPage,setEditingPage]=useState(""),[editingSection,setEditingSection]=useState(""),[editingNav,setEditingNav]=useState(""),[message,setMessage]=useState("Carregando..."),[uploading,setUploading]=useState(false),[authorized,setAuthorized]=useState<boolean|null>(null);
 async function load(){try{const[p,n,l]=await Promise.all([adminFetch<{pages:Page[]}>("/content/admin/pages"),adminFetch<{items:Nav[]}>("/content/admin/navigation"),adminFetch<{plans:Plan[]}>("/content/admin/plans").catch(()=>({plans:[]}))]);setPages(p.pages||[]);setNavigation(n.items||[]);setPlans(l.plans||[]);setAuthorized(true);setMessage("Conteúdo sincronizado com o banco.")}catch(e){if(e instanceof AdminFetchError&&(e.status===401||e.status===403))setAuthorized(false);setMessage(e instanceof Error?e.message:"Falha ao carregar CMS.")}}
 useEffect(()=>{void load()},[]);
 async function savePage(e:FormEvent){e.preventDefault();try{await adminFetch(`/content/admin/pages${editingPage?`/${editingPage}`:""}`,{method:editingPage?"PATCH":"POST",body:JSON.stringify(pageForm)});setPageForm({...blankPage});setEditingPage("");await load()}catch(x){setMessage(x instanceof Error?x.message:"Erro ao salvar página.")}}
 async function saveSection(e:FormEvent){e.preventDefault();try{await adminFetch(`/content/admin/sections${editingSection?`/${editingSection}`:""}`,{method:editingSection?"PATCH":"POST",body:JSON.stringify(sectionForm)});setSectionForm({...blankSection});setEditingSection("");await load()}catch(x){setMessage(x instanceof Error?x.message:"Erro ao salvar seção.")}}
 async function saveNav(e:FormEvent){e.preventDefault();try{await adminFetch(`/content/admin/navigation${editingNav?`/${editingNav}`:""}`,{method:editingNav?"PATCH":"POST",body:JSON.stringify(navForm)});setNavForm({location:"header",label:"",href:"",sortOrder:0,visible:true});setEditingNav("");await load()}catch(x){setMessage(x instanceof Error?x.message:"Erro ao salvar menu.")}}
 async function remove(path:string,label:string){if(!confirm(`Remover ${label}?`))return;try{await adminFetch(path,{method:"DELETE"});await load()}catch(x){setMessage(x instanceof Error?x.message:"Erro ao remover.")}}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setUploading(true);try{const form=new FormData();form.append("file",file);const response=await fetch("/api/content/admin/assets",{method:"POST",credentials:"include",body:form});const data=await response.json();if(!response.ok)throw new Error(data.message);setSectionForm(v=>({...v,imageUrl:data.asset.file_url}));setMessage("Imagem enviada.")}catch(x){setMessage(x instanceof Error?x.message:"Falha no upload.")}finally{setUploading(false)}}
 async function savePlan(plan:Plan){try{await adminFetch(`/content/admin/plans/${plan.id}`,{method:"PATCH",body:JSON.stringify({seatsLimit:plan.seats_limit,creditsLimit:plan.credits_limit,modules:plan.modules,features:plan.features})});setMessage(`Plano ${plan.plan} atualizado.`)}catch(x){setMessage(x instanceof Error?x.message:"Erro ao salvar plano.")}}
 const input="w-full rounded-lg border border-line bg-ink px-3 py-2.5 text-sm text-white outline-none focus:border-electric";const button="inline-flex items-center justify-center gap-2 rounded-lg bg-electric px-4 py-2.5 text-sm font-bold text-white";const icon="rounded-lg border border-line p-2";
 if(authorized===null)return <main className="min-h-screen bg-ink p-4 text-white md:p-8"><p className="rounded-xl border border-line bg-panel p-6">Validando acesso administrativo...</p></main>;
 if(authorized===false)return <main className="min-h-screen bg-ink p-4 text-white md:p-8"><section className="rounded-xl border border-rose-400/30 bg-panel p-6"><h1 className="text-xl font-bold">Acesso restrito</h1><p className="mt-2 text-slate-300">Somente Owner ou Administrador pode gerenciar conteúdo público.</p><Link href="/admin" className={`${button} mt-4`}>Voltar ao Administrador</Link></section></main>;
 return <main className="min-h-screen bg-ink p-4 text-white md:p-8"><header className="rounded-xl border border-line bg-panel p-5"><div className="flex flex-wrap items-center justify-between gap-4"><Logo variant="full" height={46}/><div className="flex gap-2"><Link href="/admin" className={icon}>Usuários, permissões e APIs</Link><Link href="/admin/blog" className={icon}>Blog</Link></div></div><h1 className="mt-5 text-2xl font-black">Conteúdo, interface e publicação</h1><p className="mt-2 text-sm text-slate-400">Páginas, seções, imagens, menus, planos e módulos sem alteração de código.</p><p className="mt-3 rounded-lg border border-cyan/20 bg-cyan/5 p-3 text-sm text-cyan">{message}</p></header>
 <nav className="my-5 flex flex-wrap gap-2">{[["pages",LayoutTemplate,"Páginas e seções"],["navigation",Menu,"Menus"],["plans",Settings,"Planos e módulos"]].map(([k,I,l])=><button key={String(k)} onClick={()=>setArea(k as typeof area)} className={`${area===k?"bg-electric":"border border-line bg-panel"} inline-flex items-center gap-2 rounded-lg px-4 py-3 text-sm font-bold`}><I className="h-4 w-4"/>{String(l)}</button>)}</nav>
 {area==="pages"&&<div className="grid gap-5 xl:grid-cols-[410px_1fr]"><div className="space-y-5"><form onSubmit={savePage} className="space-y-3 rounded-xl border border-line bg-panel p-4"><h2 className="font-bold">{editingPage?"Editar página":"Nova página/aba"}</h2><input className={input} required placeholder="Slug: contato, solucoes..." value={pageForm.slug} onChange={e=>setPageForm({...pageForm,slug:e.target.value})}/><input className={input} required placeholder="Título" value={pageForm.title} onChange={e=>setPageForm({...pageForm,title:e.target.value})}/><input className={input} placeholder="Subtítulo" value={pageForm.subtitle} onChange={e=>setPageForm({...pageForm,subtitle:e.target.value})}/><div className="grid grid-cols-2 gap-2"><select className={input} value={pageForm.pageType} onChange={e=>setPageForm({...pageForm,pageType:e.target.value})}><option value="institutional">Institucional</option><option value="home">Home</option><option value="manual">Manual</option><option value="pricing">Preços</option></select><select className={input} value={pageForm.status} onChange={e=>setPageForm({...pageForm,status:e.target.value as typeof pageForm.status})}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="hidden">Oculto</option></select></div><input className={input} placeholder="SEO title" value={pageForm.seoTitle} onChange={e=>setPageForm({...pageForm,seoTitle:e.target.value})}/><textarea className={input} placeholder="SEO description" value={pageForm.seoDescription} onChange={e=>setPageForm({...pageForm,seoDescription:e.target.value})}/><button className={button}><Save className="h-4 w-4"/>Salvar página</button></form>
 <form onSubmit={saveSection} className="space-y-3 rounded-xl border border-line bg-panel p-4"><h2 className="font-bold">{editingSection?"Editar seção":"Nova seção"}</h2><select className={input} required value={sectionForm.pageId} onChange={e=>setSectionForm({...sectionForm,pageId:e.target.value})}><option value="">Selecione a página</option>{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className={input} required placeholder="Chave única" value={sectionForm.sectionKey} onChange={e=>setSectionForm({...sectionForm,sectionKey:e.target.value})}/><select className={input} value={sectionForm.sectionType} onChange={e=>setSectionForm({...sectionForm,sectionType:e.target.value})}><option value="hero">Hero</option><option value="content">Conteúdo</option><option value="features">Recursos</option><option value="cta">CTA</option><option value="faq">FAQ</option></select></div><input className={input} placeholder="Título" value={sectionForm.title} onChange={e=>setSectionForm({...sectionForm,title:e.target.value})}/><input className={input} placeholder="Subtítulo" value={sectionForm.subtitle} onChange={e=>setSectionForm({...sectionForm,subtitle:e.target.value})}/><RichTextEditor value={sectionForm.body} onChange={body=>setSectionForm({...sectionForm,body})} minHeight={140}/><input className={input} placeholder="URL da imagem" value={sectionForm.imageUrl} onChange={e=>setSectionForm({...sectionForm,imageUrl:e.target.value})}/><label className={`${icon} flex cursor-pointer items-center gap-2`}><ImagePlus className="h-4 w-4"/>{uploading?"Enviando...":"Anexar imagem"}<input hidden type="file" accept="image/*" onChange={upload}/></label><div className="grid grid-cols-2 gap-2"><input className={input} placeholder="Texto do botão" value={sectionForm.buttonLabel} onChange={e=>setSectionForm({...sectionForm,buttonLabel:e.target.value})}/><input className={input} placeholder="Link do botão" value={sectionForm.buttonHref} onChange={e=>setSectionForm({...sectionForm,buttonHref:e.target.value})}/></div><div className="grid grid-cols-2 items-center gap-2"><label className="text-xs text-slate-400">Ordem<input className={input} type="number" value={sectionForm.sortOrder} onChange={e=>setSectionForm({...sectionForm,sortOrder:Number(e.target.value)})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sectionForm.visible} onChange={e=>setSectionForm({...sectionForm,visible:e.target.checked})}/>Exibir seção</label></div><button className={button}><Plus className="h-4 w-4"/>Salvar seção</button></form></div>
 <div className="space-y-4">{pages.map(p=><article key={p.id} className="rounded-xl border border-line bg-panel p-4"><div className="flex justify-between gap-3"><div><span className="text-xs text-cyan">/{p.slug} · {p.status}</span><h2 className="text-lg font-bold">{p.title}</h2><p className="text-sm text-slate-400">{p.subtitle}</p></div><div className="flex gap-1"><button className={icon} onClick={()=>{setEditingPage(p.id);setPageForm({slug:p.slug,title:p.title,subtitle:p.subtitle||"",pageType:p.page_type,status:p.status,seoTitle:p.seo_title||"",seoDescription:p.seo_description||""})}}><Pencil className="h-4 w-4"/></button><button className={`${icon} text-rose-300`} onClick={()=>void remove(`/content/admin/pages/${p.id}`,"página")}><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-3 space-y-2">{(p.nodere_cms_sections||[]).sort((a,b)=>a.sort_order-b.sort_order).map(s=><div key={s.id} className="rounded-lg border border-line bg-ink p-3"><div className="flex justify-between"><div><small className="text-slate-500">{s.section_type} · {s.section_key}</small><p className="font-semibold">{s.title||"Sem título"}</p></div><div className="flex gap-1"><button className={icon} onClick={()=>{setEditingSection(s.id);setSectionForm({pageId:s.page_id,sectionKey:s.section_key,sectionType:s.section_type,title:s.title||"",subtitle:s.subtitle||"",body:s.body||"",imageUrl:s.image_url||"",buttonLabel:s.button_label||"",buttonHref:s.button_href||"",sortOrder:s.sort_order,visible:s.visible})}}><Pencil className="h-4 w-4"/></button><button className={`${icon} text-rose-300`} onClick={()=>void remove(`/content/admin/sections/${s.id}`,"seção")}><Trash2 className="h-4 w-4"/></button></div></div>{s.body&&<div className="mt-2"><RichTextPreview value={s.body}/></div>}</div>)}</div></article>)}</div></div>}
 {area==="navigation"&&<div className="grid gap-5 lg:grid-cols-[370px_1fr]"><form onSubmit={saveNav} className="space-y-3 rounded-xl border border-line bg-panel p-4"><h2 className="font-bold">{editingNav?"Editar item de menu":"Novo item de menu"}</h2><select className={input} value={navForm.location} onChange={e=>setNavForm({...navForm,location:e.target.value as Nav["location"]})}><option value="header">Cabeçalho</option><option value="footer">Rodapé</option><option value="app">Aplicativo</option></select><input className={input} required placeholder="Rótulo" value={navForm.label} onChange={e=>setNavForm({...navForm,label:e.target.value})}/><input className={input} required placeholder="/rota ou https://" value={navForm.href} onChange={e=>setNavForm({...navForm,href:e.target.value})}/><label className="text-xs text-slate-400">Ordem<input className={input} type="number" value={navForm.sortOrder} onChange={e=>setNavForm({...navForm,sortOrder:Number(e.target.value)})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={navForm.visible} onChange={e=>setNavForm({...navForm,visible:e.target.checked})}/>Exibir item</label><button className={button}><Save className="h-4 w-4"/>{editingNav?"Salvar alterações":"Adicionar"}</button></form><div className="space-y-2">{navigation.map(n=><div key={n.id} className="flex justify-between rounded-xl border border-line bg-panel p-4"><div><strong>{n.label}</strong><p className="text-xs text-slate-400">{n.location} · {n.href}</p></div><div className="flex gap-1"><button className={icon} onClick={()=>{setEditingNav(n.id);setNavForm({location:n.location,label:n.label,href:n.href,sortOrder:n.sort_order,visible:n.visible})}}><Pencil className="h-4 w-4"/></button><button className={`${icon} text-rose-300`} onClick={()=>void remove(`/content/admin/navigation/${n.id}`,"menu")}><Trash2 className="h-4 w-4"/></button></div></div>)}</div></div>}
 {area==="plans"&&<div className="grid gap-4 lg:grid-cols-2">{plans.map((p,i)=><article key={p.id} className="rounded-xl border border-line bg-panel p-4"><h2 className="text-lg font-black uppercase">{p.plan}</h2><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs text-slate-400">Usuários<input className={input} type="number" value={p.seats_limit} onChange={e=>setPlans(a=>a.map((x,j)=>j===i?{...x,seats_limit:Number(e.target.value)}:x))}/></label><label className="text-xs text-slate-400">Créditos<input className={input} type="number" value={p.credits_limit} onChange={e=>setPlans(a=>a.map((x,j)=>j===i?{...x,credits_limit:Number(e.target.value)}:x))}/></label></div><label className="mt-3 block text-xs text-slate-400">Módulos<textarea className={`${input} min-h-24`} value={(p.modules||[]).join(", ")} onChange={e=>setPlans(a=>a.map((x,j)=>j===i?{...x,modules:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)}:x))}/></label><button className={`${button} mt-3`} onClick={()=>void savePlan(p)}><Save className="h-4 w-4"/>Salvar plano</button></article>)}</div>}
 </main>
}
