import { Company } from "../types.js";

export const companies: Company[] = [
  {
    id: "cmp-001",
    name: "Concreforte Solucoes em Concreto",
    category: "Concreteira",
    city: "Porto Alegre",
    state: "RS",
    address: "Av. Sertorio, 1840 - Porto Alegre, RS",
    phone: "+555133334444",
    whatsapp: "+5551999887766",
    website: "",
    rating: 3.9,
    reviewCount: 28,
    mapsUrl: "https://maps.google.com/?q=Concreforte+Porto+Alegre",
    hasGoogleAds: false,
    hasDescription: false,
    hasRecentPhotos: false,
    hasRecentPosts: false,
    respondsReviews: false,
    hasSsl: false,
    isResponsive: false,
    pageSpeed: 0,
    metaPixel: false,
    googleTagManager: false,
    googleAnalytics: false,
    seoBasics: false,
    status: "Novo Lead",
    score: 92,
    opportunityLevel: "Alta",
    detectedOpportunities: [
      "Empresa possui nota 3.9 e nao responde avaliacoes.",
      "Empresa sem site e sem Google Ads detectado.",
      "Perfil Google incompleto e sem fotos recentes."
    ],
    suggestions: [
      "Criar landing page local com WhatsApp e prova social.",
      "Otimizar descricao e categorias do Google Business.",
      "Implantar rotina de respostas e captura de avaliacoes."
    ],
    notes: [],
    createdAt: "2026-05-19T12:00:00.000Z",
    updatedAt: "2026-05-22T11:00:00.000Z"
  },
  {
    id: "cmp-002",
    name: "Clinica Sorriso Sul",
    category: "Clinica odontologica",
    city: "Caxias do Sul",
    state: "RS",
    address: "Rua Sinimbu, 820 - Caxias do Sul, RS",
    phone: "+555430001111",
    whatsapp: "",
    website: "https://example.com",
    rating: 4.1,
    reviewCount: 42,
    mapsUrl: "https://maps.google.com/?q=Clinica+Sorriso+Sul",
    hasGoogleAds: false,
    hasDescription: true,
    hasRecentPhotos: true,
    hasRecentPosts: false,
    respondsReviews: false,
    hasSsl: true,
    isResponsive: true,
    pageSpeed: 51,
    metaPixel: false,
    googleTagManager: true,
    googleAnalytics: true,
    seoBasics: true,
    status: "Contatado",
    score: 72,
    opportunityLevel: "Alta",
    detectedOpportunities: [
      "Menos de 50 avaliacoes em segmento altamente competitivo.",
      "Nao foram detectados Google Ads ativos.",
      "Site lento para mobile segundo PageSpeed."
    ],
    suggestions: [
      "Criar campanha Google Ads para intencao local.",
      "Melhorar Core Web Vitals e pagina de agendamento.",
      "Ativar WhatsApp Business como canal principal."
    ],
    notes: [
      {
        id: "note-001",
        companyId: "cmp-002",
        body: "Contato inicial feito. Retornar com diagnostico visual.",
        createdAt: "2026-05-21T14:10:00.000Z"
      }
    ],
    lastContactAt: "2026-05-21T14:10:00.000Z",
    createdAt: "2026-05-18T10:30:00.000Z",
    updatedAt: "2026-05-22T10:20:00.000Z"
  },
  {
    id: "cmp-003",
    name: "Mecanica Avenida",
    category: "Oficina mecanica",
    city: "Florianopolis",
    state: "SC",
    address: "Av. Mauro Ramos, 1550 - Florianopolis, SC",
    phone: "+554832221234",
    whatsapp: "+5548999990000",
    website: "https://example.org",
    rating: 4.6,
    reviewCount: 168,
    mapsUrl: "https://maps.google.com/?q=Mecanica+Avenida+Florianopolis",
    hasGoogleAds: true,
    hasDescription: true,
    hasRecentPhotos: true,
    hasRecentPosts: true,
    respondsReviews: true,
    hasSsl: true,
    isResponsive: true,
    pageSpeed: 78,
    metaPixel: true,
    googleTagManager: true,
    googleAnalytics: true,
    seoBasics: true,
    status: "Em negociação",
    score: 34,
    opportunityLevel: "Baixa",
    detectedOpportunities: ["Perfil bom, oportunidade focada em escala de midia paga."],
    suggestions: ["Oferecer auditoria de campanhas e expansao por bairros."],
    notes: [],
    createdAt: "2026-05-17T09:00:00.000Z",
    updatedAt: "2026-05-22T09:45:00.000Z"
  }
];
