import { ManualClient } from "./ManualClient";
import { getPublicPage } from "@/lib/publicContent";

const sections = [
  ["1. Visão geral", "O NODERE é um sistema operacional comercial AI-first. Após o login, a entrada principal é a NODERE AI em /ai; Dashboard, prospecção, empresas, CRM, agenda, propostas, relatórios e configurações continuam como módulos operacionais. A IA consulta dados reais do workspace por ferramentas autorizadas e só confirma uma alteração quando recebe um recibo de sucesso."],
  ["2. Dashboard", "Mostra indicadores reais vindos do backend: empresas encontradas, baixa avaliação, sem site, sem Google Ads, sem WhatsApp, sem descrição, sem fotos recentes, leads quentes, score médio e atalhos para busca e CRM."],
  ["3. Busca de empresas", "Use a aba Busca de empresas para pesquisar por nome, segmento, cidade, estado, país, palavra-chave, CNPJ ou raio geográfico. A busca passa pelo backend seguro, usa Google Places, tenta lotes ampliados e deduplica por Place ID. Empresas salvas deixam de aparecer na lista local. A página também exibe um Google Maps visual embutido; ao clicar em uma empresa na lista lateral do mapa, a visualização centraliza aquela empresa ou região sem expor chave no frontend."],
  ["4. Ações em massa", "Na tabela de busca você pode selecionar resultados, salvar selecionadas no CRM, ignorar resultados, exportar CSV e gerar relatório PDF NODERE com cabeçalho visual."],
  ["5. CRM e funil", "O CRM usa drag and drop e uma ordem canônica de etapas: Novo Lead, Qualificado, Contatado, Diagnóstico enviado, Reunião marcada, Proposta enviada, Negociação, Fechado e Perdido. Os percentuais mostram progressão acumulada entre etapas e nunca ultrapassam 100%. A personalização fica recolhida em Personalizar funil: você pode criar, renomear, remover etapas vazias e escolher cores. Todas as etapas têm rolagem vertical própria e encaixe horizontal; etapas com leads não podem ser removidas para evitar perda operacional."],
  ["6. Ficha 360", "A ficha canônica reúne visão geral, histórico, contatos, briefing, negociações, produtos, propostas, comunicações, agenda, IA, pesquisa com fontes e arquivos. Ao abrir uma empresa a partir da prospecção, a NODERE primeiro salva ou resolve duplicidades e só então navega para o registro interno persistido."],
  ["7. Observações e histórico", "Registre atividades por tipo: ligação, WhatsApp, e-mail, reunião, proposta, interno e observação geral. Informe data e hora, responsável, próxima ação e observações detalhadas no editor rico. Cada nota fica vinculada ao lead, salva no backend/Supabase e listada em ordem cronológica."],
  ["8. Agenda e notificações", "A agenda fica dentro do CRM/ficha do cliente para evitar duplicidade de navegação. Crie follow-ups com data/hora, prioridade e canal. O sininho no topo lista tarefas vencidas ou de hoje. O navegador pode pedir permissão para notificação local ao criar um follow-up. O calendário usa o tema oficial NODERE: no modo escuro, células, cabeçalhos, botões, grade, eventos e visualizações mês/semana/dia/agenda permanecem escuros e legíveis; no modo claro, os mesmos elementos usam fundos claros, bordas suaves e contraste adequado."],
  ["9. NODERE AI", "Use /ai para conversar com agentes comerciais, consultar o histórico persistido e recolher os painéis laterais ou ativar o modo foco. Em celular e tablet, histórico e detalhes abrem como drawers e ficam fechados por padrão. Conversas podem ser movidas para a Lixeira e restauradas; a operação é reversível e isolada pelo workspace. A escolha acontece em três níveis: agente, roteamento automático/manual e modelo permitido. Alterações persistentes exigem aprovação e recibo. A conta interna do proprietário mede uso técnico sem saldo artificial ou bloqueio comercial; limites e créditos reais do provedor continuam válidos."],
  ["10. Propostas, contratos e PDFs", "O fluxo comercial é dividido em cliente, tipo de documento, produtos/serviços reais, preços e descontos, escopo, condições, validade, preview, geração e histórico de versões. Um modelo opcional apenas preenche o rascunho: nunca cria proposta, contrato, PDF, evento ou mudança de etapa. Nova versão preserva o snapshot anterior e exige motivo. Custo, margem e limite de desconto vêm do catálogo; impostos são mostrados como não configurados quando não existe regra aplicável. Proposta e contrato têm PDFs A4 distintos no servidor, e observações internas nunca aparecem no documento do cliente."],
  ["11. WhatsApp", "O botão WhatsApp abre wa.me com mensagem pronta. Sem WhatsApp Cloud API, o retorno precisa ser registrado manualmente na Caixa de entrada ou nas observações do cliente."],
  ["12. Pesquisa pública com fontes", "Na ficha 360, use Pesquisa com fontes para consultar informações públicas autorizadas. A NODERE mostra as URLs consultadas, confiança de identidade e dos dados, separa fatos de inferências e nunca persiste sugestões sem aprovação explícita."],
  ["13. Integrações", "A tela Integrações mostra o estado real de Google Places, Maps, PageSpeed, OpenAI, Supabase, WhatsApp, e-mail e serviços habilitados. Credenciais ficam protegidas no backend e nunca são expostas no frontend público."],
  ["14. Tema, fonte e layout", "Em Configurações você altera tema Claro, Escuro ou Sistema, fonte, tamanho de fonte, densidade, layout, visual e cor principal. A densidade confortável é o padrão: cabeçalho de 72px, conteúdo com largura máxima, títulos e seções com hierarquia mais clara e áreas clicáveis visíveis. No topo do sistema, abra Preferências rápidas pelo botão do usuário para alternar tema, tamanho da fonte, densidade, foto e nome exibido. A escolha é salva em nodere_settings, reaplicada antes da renderização e sincronizada com o backend quando disponível. A preferência permanece ao trocar páginas, atualizar o navegador, fazer logout/login, reabrir o navegador, usar mobile ou PWA."],
  ["15. App no celular/PWA", "No celular, a navegação prioriza NODERE AI, Dashboard, Prospecção e CRM; os demais módulos ficam no menu. O app instalado abre em /ai. As telas usam altura dinâmica do dispositivo. Para instalar, toque em Compartilhar/Instalar app e confirme NODERE. Por segurança, páginas autenticadas e respostas com dados do workspace nunca são gravadas no cache do service worker; sem rede, o app mostra a tela offline e exige conexão para voltar aos dados privados."],
  ["16. Login, sessão e usuários", "O acesso é protegido. Antes de exibir qualquer tela interna, o NODERE valida a sessão no backend; token inválido ou expirado redireciona para /login com o destino original. O endpoint de sessão só grava o cookie httpOnly depois que o backend confirma o usuário e o workspace. As chamadas internas usam um proxy seguro no mesmo domínio, autenticado pelo cookie; o token de acesso não é persistido em localStorage. Falha temporária mostra uma tela de nova tentativa sem revelar dados. Administradores acessam apenas os módulos liberados do workspace."],
  ["17. Busca avançada", "A busca possui três modos: Google Places local, CNPJ direto e Global/Internacional. Google Places usa backend seguro e filtra empresas já salvas. CNPJ direto consulta ReceitaWS e retorna uma empresa pronta para salvar. A busca internacional usa país/região quando informado."],
  ["18. Resultado de busca limpo", "Ao iniciar uma nova busca, resultados anteriores não salvos são apagados imediatamente. Apenas leads salvos no CRM permanecem na base, evitando mistura entre pesquisas diferentes."],
  ["19. LinkedIn", "Links do LinkedIn usam somente o nome da empresa. O sistema remove domínio, protocolo e complementos antes de montar a busca, evitando consultas como empresa.com."],
  ["20. Telefone e WhatsApp", "Telefones fixos brasileiros ficam em telefone principal e não aparecem no botão WhatsApp. O WhatsApp só é preenchido automaticamente quando o número tem DDD + celular com 9 dígitos iniciado por 9."],
  ["21. Contatos", "Na ficha comercial, a aba Contatos permite cadastrar nome, cargo/função, telefone, WhatsApp, e-mail, LinkedIn, nível de influência e observações. Use Decisor para quem aprova, Influenciador para quem recomenda e Operacional para quem participa da execução. O cadastro fica vinculado ao workspace e à empresa."],
  ["22. Calendário", "A página Calendário permite criar eventos reais com tipo, prioridade, data inicial, data final e notas. Os eventos são salvos em Supabase pela rota /api/calendar. Integrações Google Calendar e Outlook ficam preparadas por variáveis de ambiente futuras. A visualização é compartilhada com a Agenda da Ficha 360 e com o Calendário de conteúdo do Marketing; por isso, qualquer ajuste de tema no calendário deve ser validado nas três áreas, alternando Claro/Escuro e conferindo que não há células brancas indevidas no modo escuro."],
  ["23. Catálogo", "A página Catálogo permite criar produtos e serviços com código automático, categoria, preço, custo, margem, comissão, descrição completa, benefícios, diferenciais, público-alvo, dados técnicos, dados de estoque, escopo, entregáveis e SLA. O catálogo usa /api/catalog e os itens podem ser vinculados ao cliente pela rota de contratos."],
  ["24. Comunicações", "A Ficha 360 possui uma única aba Comunicações para WhatsApp e e-mail, compartilhando histórico e o compositor canônico. Modelos são apenas modelos; compor gera rascunho na outbox; aprovar envia somente quando consentimento, horário, variáveis e provedor estiverem válidos. E-mails aceitam até 10 anexos e 20 MB da área protegida. Sem SMTP configurado, o rascunho é preservado e nenhum envio é simulado."],
  ["25. Termos e privacidade", "As páginas /terms e /privacy ficam acessíveis sem login e documentam uso, armazenamento, isolamento por workspace e direitos LGPD. Elas também aparecem no rodapé do login e do app."],
  ["26. Importação CSV/XLSX", "Na aba Busca de empresas, use Importar empresas para enviar CSV ou XLSX moderno. O formato XLS antigo não é aceito: converta-o para XLSX ou CSV antes do envio. O limite é 4 MB, 5.000 registros e 100 colunas, compatível com o proxy seguro da Vercel. O backend valida email, normaliza CNPJ/telefone, evita duplicidade por CNPJ ou nome+cidade e registra a importação quando o banco está disponível. O modelo CSV fica em /api/companies/import/template."],
  ["27. Relatórios com filtros", "A página Relatórios usa dados reais dos endpoints /api/reports/summary, /funnel, /timeline, /segments, /cities, /origin e /intelligence. Use filtros por período, operador, empresa, segmento, cidade/UF, origem do lead, etapa do funil, temperatura, plano contratado e nível de acesso. Administradores visualizam dados consolidados do workspace; usuários comuns visualizam conforme permissões e plano."],
  ["28. Usuários, permissões e auditoria", "Owner/Admin criam usuários e consultam logs de auditoria do workspace. Perfis: Owner, Administrador, Operador e Visualizador. A condição de proprietário interno é gravada pelo UUID imutável do Supabase Auth; nenhum e-mail no código concede privilégio. A conta interna tem isenção comercial formal, medição técnica habilitada e limites do provedor preservados."],
  ["29. Navegação operacional", "O menu mostra somente módulos operacionais: AI, Dashboard, Prospecção e pesquisa, Funil, Empresas, Comunicações, Agenda, Briefings, Propostas, Catálogo, Relatórios e administração autorizada. Protótipos e telas sem motor real não aparecem como produto disponível. Arquivo e Lixeira ficam no fluxo de ciclo de vida, e não como módulo principal."],
  ["30. PDFs e documentos", "Relatórios de empresas, ficha comercial/ficha cliente, propostas e contratos usam documento branco, texto escuro, cabeçalho NODERE, logo oficial quando disponível, divisores visuais, blocos organizados, rodapé com o endereço público configurado e paginação. O PDF da Ficha Cliente organiza dados da empresa, score e oportunidade, sinais digitais, oportunidades, sugestões, histórico, agenda e documentos anexados. Textos formatados são limpos para não exibir HTML cru, markdown, símbolos quebrados ou quebras literais. A aparência do PDF é independente do tema claro/escuro da interface."],
  ["31. Cadastro manual de empresa", "Na página Empresas, abra Cadastro manual para criar uma empresa sem depender de fontes externas. Informe nome fantasia, razão social, CNPJ, endereço, telefone fixo, WhatsApp celular, redes sociais, responsável, status, temperatura e observações. Ao salvar, a empresa é gravada no Supabase e abre diretamente na ficha 360."],
  ["32. Tema claro e contraste", "O tema claro usa regras globais de contraste para botões, ícones, campos, ações de CSV/PDF/salvar/exportar e cards. Se algum botão parecer apagado, ajuste o tema em Configurações e verifique se o navegador carregou a versão mais recente."],
  ["33. Editor de texto", "Campos de observação, histórico, agenda, contatos, negociações, propostas, contratos, WhatsApp, marketing, calendário de conteúdo, posts, campanhas, templates, Admin/CMS, blog, páginas institucionais, e-mails, relatórios com notas e documentos usam o editor rico padronizado do NODERE quando permitem conteúdo formatado. A barra do editor é organizada em grupos: fonte/tamanho, estilos, alinhamento, listas, cor/destaque/espaçamento, link/imagem e limpar/desfazer/refazer. Owner, Administrador e Operador editam conforme permissões do módulo; Visualizador acessa somente leitura quando a regra da tela permitir. Em telas pequenas, os grupos quebram em linhas para não cortar botões nem gerar rolagem lateral. Ao salvar, a formatação é preservada no backend e exibida sem mostrar tags HTML indevidas. PDFs de propostas, contratos e documentos usam o conteúdo salvo como origem, limpam marcações internas quando necessário e não exibem observações internas ao cliente. Se a toolbar parecer desalinhada, atualize a página e confirme que está usando a versão mais recente; se algum texto parecer sem formatação, confira se o conteúdo foi salvo e se a sessão continua autenticada."],
  ["34. Negociações", "Na ficha comercial, a aba Negociações permite registrar valor, produto ou serviço, etapa, probabilidade, previsão de fechamento, motivo de perda, próxima ação e observações formatadas. Cada negociação fica salva como documento vinculado ao lead e pode ser consultada junto aos serviços contratados."],
  ["35. Administrador e conteúdo público", "A aba Administrador concentra gestão de usuários, permissões, planos, módulos, integrações e conteúdos editáveis. Blog e páginas públicas usam o fluxo canônico Admin > Conteúdo; o atalho histórico /admin/blog redireciona para esse editor. Publique somente alterações revisadas. Conteúdos dinâmicos exigem as tabelas oficiais do CMS no banco; enquanto o schema não estiver instalado, a interface deve informar a pendência e não simular persistência."],
  ["36. Relatórios executivos", "A aba Relatórios Executivos consolida dados reais do CRM, funil, origem dos leads, operadores, cidades, segmentos, score médio, oportunidades, atividades e exportações PDF/CSV. Sempre que uma funcionalidade, campo, permissão, status, proposta, contrato, produto/serviço, integração ou fluxo comercial mudar, os relatórios precisam ser revisados para manter indicadores, filtros e nomenclaturas coerentes com o sistema real."],
  ["37. Regra de atualização obrigatória", "Toda alteração relevante no NODERE deve revisar Relatórios Executivos e Ajuda / Manual NODERE antes de ser considerada concluída. O relatório final da tarefa deve informar se ambos foram revisados, quais ajustes foram aplicados, o que não exigiu atualização e se ainda existe pendência. A regra oficial fica no arquivo REGRA_ATUALIZACAO_RELATORIOS_MANUAL.md do repositório."],
  ["38. Ícones, botões e ações visuais", "A iconografia NODERE usa símbolos Lucide semanticamente únicos, traço e escala consistentes, área clicável acessível, tooltip em controles compactos e contraste verificado nos temas claro e escuro. O estado inativo é discreto; cor e superfície aparecem somente para seleção, alerta ou prioridade, evitando ornamentação repetitiva. NODERE AI usa Sparkles, Dashboard usa Gauge, Funil usa Waypoints, Empresas usa Building, Comunicações usa MessageCircle, Briefings usa Clipboard, Propostas usa FileSignature, Catálogo usa Boxes, Relatórios usa Chart e Administração usa símbolos próprios. Ações sem texto sempre exigem aria-label e title. No Kanban, editar, excluir, salvar e cancelar usam área compacta padronizada e continuam centralizados em desktop, tablet, mobile e zoom."],
  ["39. Arquitetura e deploy seguro", "A fonte oficial do NODERE atual é apps/web para frontend, apps/api para backend, Supabase PostgreSQL para banco, Vercel projeto web com Root Directory apps/web e Render serviço nodere-api. O deploy pela raiz do repositório é bloqueado para impedir publicação da versão legada em dist/index.html. GitHub Pages não é canal oficial de produção. Links novos devem seguir a matriz de rotas canônicas documentada em docs/ROTAS_CANONICAS_NODERE.md; aliases históricos permanecem apenas por compatibilidade."],
  ["40. Erros comuns", "Limite de IA indica falta de crédito no provedor configurado. Integração pendente indica credencial ausente ou incompleta. Login obrigatório indica rota protegida, sessão expirada ou usuário sem vínculo válido com o workspace. Serviço temporariamente indisponível mostra Nova tentativa e não libera a área privada. Arquivo XLS antigo deve ser convertido para XLSX/CSV. Busca vazia pode indicar limite da API, restrição de chave ou termo muito específico."],
  ["41. Auditoria final e segurança", "As rotas privadas validam sessão, usuário ativo e workspace antes de dados ou mutações. O OWNER canônico é protegido contra rebaixamento, desativação e duplicidade. RLS separa tenants; tabelas sensíveis de autenticação, IA, carteira, ledger e faturamento permanecem acessíveis somente pelo backend. Credenciais ficam no servidor, o cache PWA não armazena respostas privadas, pesquisas públicas bloqueiam destinos internos e redirecionamentos inseguros, e importações são validadas. Toda publicação verifica saúde da API, sessão, isolamento, PDFs, CRM, pesquisa, comunicações e rollback."],
  ["42. Agentes, modelos, créditos e aprovações", "Copiloto comercial coordena o fluxo geral; Analista de prospecção prioriza contas; Coach de pipeline recomenda avanços; Estrategista de propostas estrutura argumentos. Cada agente oferece somente modelos e ferramentas autorizados. O catálogo é atualizado pelo endpoint do provedor e registra disponibilidade, capacidades, horário e erro. A chave fica somente no backend; usuários não devem colar segredos nas configurações do workspace."],
  ["43. Perfis e permissões", "O login aceita contas válidas do Supabase Auth e contas protegidas da plataforma, sempre vinculando a sessão ao workspace correto. Owner e Admin têm acesso integral; Operador respeita os módulos liberados; Visualizador usa leitura; perfil Restricted não entra. As permissões são verificadas no menu e novamente pela API."],
  ["44. Ditado PT-BR", "Ao focar um campo de texto curto, longo ou editor aplicável, use o botão de microfone. A fala é reconhecida em português do Brasil e aparece em uma janela de revisão editável sem apagar o conteúdo existente. Escolha substituir, adicionar ao final ou cancelar. O controle acompanha o campo selecionado e é removido ao mudar de rota; senhas, tokens, chaves de API, cartão, banco e PIX nunca recebem ditado."],
  ["45. Eventos e ciclo de vida", "Criação de lead, mudança de etapa, atividade, tarefa, proposta, contrato, briefing, pesquisa e comunicação emitem eventos de domínio auditáveis. Arquivar e mover para a lixeira são reversíveis; exclusão definitiva exige permissão, motivo, confirmação e ausência de impedimento legal. Arquivos da Ficha 360 aceitam formatos permitidos, recebem checksum SHA-256, usam download assinado de curta duração e permanecem recuperáveis na lixeira. Dados de homologação usam registro por lote para limpeza determinística."],
  ["46. Workspace e dados reais", "O workspace canônico da operação é resolvido pela sessão do usuário e nunca por indicador visual. Se um módulo aparecer zerado, não crie registros artificiais: confirme o vínculo do usuário, o workspace, a política RLS e a origem persistida. O Dashboard, Empresas, Funil, Ficha 360 e Relatórios devem ler o mesmo conjunto canônico, sem duplicação nem filtros legados ocultando registros válidos."]
];

export default async function ManualPage() {
  const page = await getPublicPage("manual");
  const publishedSections = page?.nodere_cms_sections?.map((section) => [section.title || "Orientação", section.body || section.subtitle || ""]);
  return <ManualClient sections={publishedSections?.length ? publishedSections : sections} />;
}
