import { ManualClient } from "./ManualClient";
import { getPublicPage } from "@/lib/publicContent";

const sections = [
  ["1. Visão geral", "O NODERE centraliza busca de empresas reais, CRM, funil comercial, agenda, WhatsApp via web, IA, relatórios, propostas, contratos e status de integrações. O fluxo principal é: buscar empresa, salvar lead, abrir ficha, registrar histórico, agendar follow-up, mover no funil e gerar material comercial."],
  ["2. Dashboard", "Mostra indicadores reais vindos do backend: empresas encontradas, baixa avaliação, sem site, sem Google Ads, sem WhatsApp, sem descrição, sem fotos recentes, leads quentes, score médio e atalhos para busca e CRM."],
  ["3. Busca de empresas", "Use a aba Busca de empresas para pesquisar por nome, segmento, cidade, estado, país, palavra-chave, CNPJ ou raio geográfico. A busca passa pelo backend seguro, usa Google Places, tenta lotes ampliados e deduplica por Place ID. Empresas salvas deixam de aparecer na lista local. A página também exibe um Google Maps visual embutido; ao clicar em uma empresa na lista lateral do mapa, a visualização centraliza aquela empresa ou região sem expor chave no frontend."],
  ["4. Ações em massa", "Na tabela de busca você pode selecionar resultados, salvar selecionadas no CRM, ignorar resultados, exportar CSV e gerar relatório PDF NODERE com cabeçalho visual."],
  ["5. CRM e funil", "O CRM usa drag and drop. Você pode criar novas etapas do funil, renomear, remover etapas vazias e escolher uma cor manual para cada etapa. Todas as etapas têm rolagem vertical própria; etapas novas herdam esse comportamento automaticamente. Etapas com leads não podem ser removidas para evitar perda operacional."],
  ["6. Ficha do cliente", "A ficha reúne dados, score, telefone, site, Google Maps, observações, agenda, IA/editor, documentos, WhatsApp, auditoria digital e inteligência Google quando configurada. Ao abrir a ficha a partir da Busca de empresas, o NODERE primeiro salva ou resolve o lead duplicado no CRM e só então navega para o registro persistido; isso evita abrir fichas com identificadores externos do Google Places/Discovery que ainda não existem no banco. Se uma URL antiga com ID externo encontrar um registro já salvo, a página redireciona automaticamente para o ID interno canônico."],
  ["7. Observações e histórico", "Registre atividades por tipo: ligação, WhatsApp, e-mail, reunião, proposta, interno e observação geral. Informe data e hora, responsável, próxima ação e observações detalhadas no editor rico. Cada nota fica vinculada ao lead, salva no backend/Supabase e listada em ordem cronológica."],
  ["8. Agenda e notificações", "A agenda fica dentro do CRM/ficha do cliente para evitar duplicidade de navegação. Crie follow-ups com data/hora, prioridade e canal. O sininho no topo lista tarefas vencidas ou de hoje. O navegador pode pedir permissão para notificação local ao criar um follow-up."],
  ["9. IA / Editor", "Escolha o tipo de geração: resumo, WhatsApp, email, proposta, contrato simples, diagnóstico ou objeções. A IA usa OpenAI via backend. Se a OpenAI estiver sem crédito, o sistema mostra erro real e não inventa resposta."],
  ["10. Propostas, contratos e PDFs", "Monte propostas e contratos a partir dos produtos/serviços ativos do catálogo oficial. Nome, descrição, condições, forma de pagamento e prazo vêm do cadastro; no documento você ajusta apenas preço/desconto permitido e observações comerciais. Observações internas não aparecem no PDF do cliente."],
  ["11. WhatsApp", "O botão WhatsApp abre wa.me com mensagem pronta. Sem WhatsApp Cloud API, o retorno precisa ser registrado manualmente na Caixa de entrada ou nas observações do cliente."],
  ["12. Enriquecimento CNPJ e decisores", "Na ficha do lead, use a aba Apollo/Econodata para consultar dados externos. Apollo exige APOLLO_API_KEY e plano/API com acesso a organizations/people search/enrichment; se a conta retornar API_INACCESSIBLE, o problema é permissão/plano do Apollo e não o botão do NODERE. Econodata exige ECONODATA_API_KEY e ECONODATA_API_URL oficial do contrato. LinkedIn pode vir do site do cliente, Apollo ou Econodata; quando não houver link confirmado, o sistema abre uma busca assistida somente pelo nome da empresa para você validar manualmente."],
  ["13. Integrações", "A tela Integrações mostra status real de Google Places, Maps, PageSpeed, OpenAI, Supabase, WhatsApp, Econodata e Apollo. Credenciais ficam protegidas no ambiente técnico ou no modo Admin; nunca no frontend público."],
  ["14. Tema, fonte e layout", "Em Configurações você altera tema Claro, Escuro ou Sistema, fonte, tamanho de fonte, densidade, layout, visual e cor principal. No topo do sistema, abra Preferências rápidas pelo botão do usuário para alternar rapidamente tema, tamanho da fonte, densidade, foto e nome exibido. Internamente o NODERE usa os valores light e dark, exibidos para o usuário como Claro e Escuro. A escolha é salva em nodere_settings e chaves legadas compatíveis, reaplicada em html e body antes da renderização visual da página e sincronizada com o backend quando disponível. O tema claro mantém a mesma hierarquia visual do escuro: fundo com identidade NODERE, cards com bordas verdes suaves, badges coloridos, barras de progresso, sidebar, topbar, tabelas, abas, indicadores e editores com contraste adequado. A preferência permanece ao trocar páginas, atualizar o navegador, fazer logout/login, reabrir o navegador, usar mobile ou PWA. Se alguma tela parecer misturar claro e escuro, salve novamente em Configurações ou Preferências rápidas e atualize a página."],
  ["15. App no celular/PWA", "No celular, use o menu rolável para acessar Início, Busca, Empresas, CRM, IA, Inbox, Relatórios, Integrações, Configurações, Manual e Admin. As telas, abas, modais e drawers usam altura dinâmica do dispositivo para permitir rolagem até o fim do conteúdo sem cortar botões ou campos. O botão Sair permanece acessível na barra superior ou menu. Para instalar o PWA, abra o navegador, toque em Compartilhar/Instalar app e confirme NODERE."],
  ["16. Login, sessão e usuários", "O acesso ao sistema é protegido. Sem sessão válida, a raiz do domínio redireciona para /login e a interface pública/institucional fica oculta. Rotas internas sem sessão também redirecionam para login com o destino original. Após login, a sessão fica em cookie httpOnly e token local seguro para preservar navegação entre telas. Se aparecer login obrigatório, saia, entre novamente e confirme o workspace correto. Administradores têm acesso amplo aos módulos liberados do workspace. Termos e privacidade continuam acessíveis para suporte legal ao login."],
  ["17. Busca avançada", "A busca possui três modos: Google Places local, CNPJ direto e Global/Internacional. Google Places usa backend seguro e filtra empresas já salvas. CNPJ direto consulta ReceitaWS e retorna uma empresa pronta para salvar. A busca internacional usa país/região quando informado."],
  ["18. Resultado de busca limpo", "Ao iniciar uma nova busca, resultados anteriores não salvos são apagados imediatamente. Apenas leads salvos no CRM permanecem na base, evitando mistura entre pesquisas diferentes."],
  ["19. LinkedIn", "Links do LinkedIn usam somente o nome da empresa. O sistema remove domínio, protocolo e complementos antes de montar a busca, evitando consultas como empresa.com."],
  ["20. Telefone e WhatsApp", "Telefones fixos brasileiros ficam em telefone principal e não aparecem no botão WhatsApp. O WhatsApp só é preenchido automaticamente quando o número tem DDD + celular com 9 dígitos iniciado por 9."],
  ["21. Contatos", "Na ficha comercial, a aba Contatos permite cadastrar nome, cargo/função, telefone, WhatsApp, e-mail, LinkedIn, nível de influência e observações. Use Decisor para quem aprova, Influenciador para quem recomenda e Operacional para quem participa da execução. O cadastro fica vinculado ao workspace e à empresa."],
  ["22. Calendário", "A página Calendário permite criar eventos reais com tipo, prioridade, data inicial, data final e notas. Os eventos são salvos em Supabase pela rota /api/calendar. Integrações Google Calendar e Outlook ficam preparadas por variáveis de ambiente futuras."],
  ["23. Catálogo", "A página Catálogo permite criar produtos e serviços com código automático, categoria, preço, custo, margem, comissão, descrição completa, benefícios, diferenciais, público-alvo, dados técnicos, dados de estoque, escopo, entregáveis e SLA. O catálogo usa /api/catalog e os itens podem ser vinculados ao cliente pela rota de contratos."],
  ["24. Comunicações", "A ficha da empresa pode registrar comunicações de WhatsApp, email, ligação, reunião, LinkedIn, Instagram, nota e interno. O histórico fica cronológico e vinculado ao cliente. Quando o envio real de e-mail estiver ativo, a ficha também envia e salva o envio no histórico. Sem essa configuração, o sistema mostra pendência clara e não finge envio."],
  ["25. Termos e privacidade", "As páginas /terms e /privacy ficam acessíveis sem login e documentam uso, armazenamento, isolamento por workspace e direitos LGPD. Elas também aparecem no rodapé do login e do app."],
  ["26. Importação CSV/XLSX", "Na aba Busca de empresas, use Importar empresas para enviar arquivo CSV ou XLSX, mapear colunas e importar em massa. O backend valida email, normaliza CNPJ/telefone, evita duplicidade por CNPJ ou nome+cidade, grava no Supabase e registra a importação em download_logs quando o banco está disponível. O modelo CSV fica em /api/companies/import/template."],
  ["27. Relatórios com filtros", "A página Relatórios usa dados reais dos endpoints /api/reports/summary, /funnel, /timeline, /segments, /cities, /origin e /intelligence. Use filtros por período, operador, empresa, segmento, cidade/UF, origem do lead, etapa do funil, temperatura, plano contratado e nível de acesso. Administradores visualizam dados consolidados do workspace; usuários comuns visualizam conforme permissões e plano."],
  ["28. Usuários, permissões e auditoria", "Owner/Admin criam usuários no Administrador e podem consultar em Configurações os usuários ativos, logs de auditoria e downloads/exportações do workspace. Perfis disponíveis: Owner, Administrador, Operador e Visualizador. Visualizador é voltado para leitura e não deve receber permissões administrativas. O administrador geral validado não deve sofrer bloqueio de plano, créditos ou módulos."],
  ["29. Marketing e redes sociais", "A página Marketing possui templates de mensagem, campanhas e status das integrações sociais. Instagram/Facebook usam Meta OAuth, LinkedIn usa LinkedIn OAuth e Google Meu Negócio usa OAuth do Google Business quando as variáveis existem. mLabs aparece como atalho operacional para https://app.mlabs.com.br, pois não há API pública oficial de terceiros."],
  ["30. PDFs e documentos", "Relatórios de empresas, ficha comercial/ficha cliente, propostas e contratos usam documento branco, texto escuro, cabeçalho NODERE, logo oficial quando disponível, divisores visuais, blocos organizados, rodapé 'Gerado pelo NODERE - nodere.com.br' e paginação. O PDF da Ficha Cliente organiza dados da empresa, score e oportunidade, sinais digitais, oportunidades, sugestões, histórico, agenda e documentos anexados. Textos formatados são limpos para não exibir HTML cru, markdown, símbolos quebrados ou quebras literais. A aparência do PDF é independente do tema claro/escuro da interface."],
  ["31. Cadastro manual de empresa", "Na página Empresas, abra Cadastro manual para criar uma empresa sem depender de Google, CNPJ ou Apollo. Informe nome fantasia, razão social, CNPJ, endereço, telefone fixo, WhatsApp celular, redes sociais, responsável, status, temperatura e observações. Ao salvar, a empresa é gravada no Supabase e abre diretamente na ficha 360°."],
  ["32. Tema claro e contraste", "O tema claro usa regras globais de contraste para botões, ícones, campos, ações de CSV/PDF/salvar/exportar e cards. Se algum botão parecer apagado, ajuste o tema em Configurações e verifique se o navegador carregou a versão mais recente."],
  ["33. Editor de texto", "Campos de observação, histórico, agenda, contatos, negociações, propostas, contratos, WhatsApp, marketing, calendário de conteúdo, posts, campanhas, templates, Admin/CMS, blog, páginas institucionais, e-mails, relatórios com notas e documentos usam o editor rico padronizado do NODERE quando permitem conteúdo formatado. A barra do editor é organizada em grupos: fonte/tamanho, estilos, alinhamento, listas, cor/destaque/espaçamento, link/imagem e limpar/desfazer/refazer. Owner, Administrador e Operador editam conforme permissões do módulo; Visualizador acessa somente leitura quando a regra da tela permitir. Em telas pequenas, os grupos quebram em linhas para não cortar botões nem gerar rolagem lateral. Ao salvar, a formatação é preservada no backend e exibida sem mostrar tags HTML indevidas. PDFs de propostas, contratos e documentos usam o conteúdo salvo como origem, limpam marcações internas quando necessário e não exibem observações internas ao cliente. Se a toolbar parecer desalinhada, atualize a página e confirme que está usando a versão mais recente; se algum texto parecer sem formatação, confira se o conteúdo foi salvo e se a sessão continua autenticada."],
  ["34. Negociações", "Na ficha comercial, a aba Negociações permite registrar valor, produto ou serviço, etapa, probabilidade, previsão de fechamento, motivo de perda, próxima ação e observações formatadas. Cada negociação fica salva como documento vinculado ao lead e pode ser consultada junto aos serviços contratados."],
  ["35. Administrador e conteúdo público", "A aba Administrador concentra gestão de usuários, permissões, planos, módulos, integrações e conteúdos editáveis. Para página inicial, menus, botões, links, páginas institucionais e manual, publique somente alterações revisadas. Conteúdos dinâmicos devem persistir no banco quando o módulo de conteúdo estiver configurado."],
  ["36. Relatórios executivos", "A aba Relatórios Executivos consolida dados reais do CRM, funil, origem dos leads, operadores, cidades, segmentos, score médio, oportunidades, atividades e exportações PDF/CSV. Sempre que uma funcionalidade, campo, permissão, status, proposta, contrato, produto/serviço, integração ou fluxo comercial mudar, os relatórios precisam ser revisados para manter indicadores, filtros e nomenclaturas coerentes com o sistema real."],
  ["37. Regra de atualização obrigatória", "Toda alteração relevante no NODERE deve revisar Relatórios Executivos e Ajuda / Manual NODERE antes de ser considerada concluída. O relatório final da tarefa deve informar se ambos foram revisados, quais ajustes foram aplicados, o que não exigiu atualização e se ainda existe pendência. A regra oficial fica no arquivo REGRA_ATUALIZACAO_RELATORIOS_MANUAL.md do repositório."],
  ["38. Ícones, botões e ações visuais", "Ícones da plataforma seguem escala global NODERE para manter alinhamento em cabeçalhos, menus, sidebars, cards, tabelas, listas, formulários, modais, tooltips, filtros, áreas administrativas, editores e ações rápidas. Ícones pequenos usam 14px, ações usam 16px, ícones médios usam 18px, grandes usam 20px e destaques usam 24px. As cores dos ícones são semânticas e independentes do tema: verde para CRM/leads/ações recomendadas, azul para score/relatórios/propostas enviadas, laranja para leads quentes e WhatsApp, dourado para conversões e propostas em aberto, roxo/magenta para ausência de redes sociais, laranja escuro para ausência de Google Ads e vermelho para problemas críticos como sem site. No CRM/Kanban, lápis, lixeira, salvar e cancelar nos cabeçalhos das etapas usam ação compacta própria para permanecer centralizados, coloridos e dentro da coluna mesmo com títulos longos, tema claro/escuro ou zoom alterado. Sempre que criar uma nova ação, use componentes compartilhados como Button, Input, navegação e editor; evite style inline de width, height, strokeWidth, fontSize ou transform; use aria-label/title em botões sem texto; valide desktop, notebook, mobile e zoom 33%, 50%, 67%, 75%, 80%, 90%, 100%, 110%, 125% e 150% quando a ação estiver em área compacta."],
  ["39. Arquitetura e deploy seguro", "A fonte oficial do NODERE atual é apps/web para frontend, apps/api para backend, Supabase PostgreSQL para banco, Vercel projeto web com Root Directory apps/web e Render serviço nodere-api. O deploy pela raiz do repositório é bloqueado para impedir publicação da versão legada em dist/index.html. GitHub Pages não é canal oficial de produção. Links novos devem seguir a matriz de rotas canônicas documentada em docs/ROTAS_CANONICAS_NODERE.md; aliases históricos permanecem apenas por compatibilidade."],
  ["40. Erros comuns", "Limite de IA indica falta de crédito no provedor configurado. Integração pendente indica credencial ausente ou incompleta. Login obrigatório indica rota protegida ou sessão expirada. Busca vazia pode indicar limite da API, restrição de chave ou termo muito específico."]
];

export default async function ManualPage() {
  const page = await getPublicPage("manual");
  const publishedSections = page?.nodere_cms_sections?.map((section) => [section.title || "Orientação", section.body || section.subtitle || ""]);
  return <ManualClient sections={publishedSections?.length ? publishedSections : sections} />;
}
