import { ManualClient } from "./ManualClient";

const sections = [
  ["1. Visão geral", "O NODERE centraliza busca de empresas reais, CRM, funil comercial, agenda, WhatsApp via web, IA, relatórios, propostas, contratos e status de integrações. O fluxo principal é: buscar empresa, salvar lead, abrir ficha, registrar histórico, agendar follow-up, mover no funil e gerar material comercial."],
  ["2. Dashboard", "Mostra indicadores reais vindos do backend: empresas encontradas, baixa avaliação, sem site, sem Google Ads, sem WhatsApp, sem descrição, sem fotos recentes, leads quentes, score médio e atalhos para busca e CRM."],
  ["3. Busca de empresas", "Use a aba Busca de empresas para pesquisar por nome, segmento, cidade, estado e palavra-chave. A busca passa pelo backend seguro, usa Google Places, tenta lotes ampliados e deduplica por Place ID. Empresas salvas deixam de aparecer na lista local."],
  ["4. Ações em massa", "Na tabela de busca você pode selecionar resultados, salvar selecionadas no CRM, ignorar resultados, exportar CSV e gerar relatório PDF NODERE com cabeçalho visual."],
  ["5. CRM e funil", "O CRM usa drag and drop. Você pode criar novas etapas do funil, renomear, remover etapas vazias e escolher uma cor manual para cada etapa. Todas as etapas têm rolagem vertical própria; etapas novas herdam esse comportamento automaticamente. Etapas com leads não podem ser removidas para evitar perda operacional."],
  ["6. Ficha do cliente", "A ficha reúne dados, score, telefone, site, Google Maps, observações, agenda, IA/editor, documentos, WhatsApp, auditoria digital e inteligência Google quando configurada."],
  ["7. Observações e histórico", "Registre observações por tipo: ligação, WhatsApp, email, reunião, objeção, interno e observação geral. Cada nota fica vinculada ao lead e salva no backend/Supabase quando configurado."],
  ["8. Agenda e notificações", "A agenda fica dentro do CRM/ficha do cliente para evitar duplicidade de navegação. Crie follow-ups com data/hora, prioridade e canal. O sininho no topo lista tarefas vencidas ou de hoje. O navegador pode pedir permissão para notificação local ao criar um follow-up."],
  ["9. IA / Editor", "Escolha o tipo de geração: resumo, WhatsApp, email, proposta, contrato simples, diagnóstico ou objeções. A IA usa OpenAI via backend. Se a OpenAI estiver sem crédito, o sistema mostra erro real e não inventa resposta."],
  ["10. Propostas, contratos e PDFs", "Gere ou escreva textos no editor, revise manualmente e salve como proposta ou contrato PDF. O PDF baixado usa fundo branco, texto escuro, azul NODERE, cabeçalho com marca NODERE e rodapé nodere.com.br. Ele fica salvo na ficha do cliente como documento."],
  ["11. WhatsApp", "O botão WhatsApp abre wa.me com mensagem pronta. Sem WhatsApp Cloud API, o retorno precisa ser registrado manualmente na Caixa de entrada ou nas observações do cliente."],
  ["12. Enriquecimento CNPJ e decisores", "Na ficha do lead, use a aba Apollo/Econodata para consultar dados externos. Apollo exige APOLLO_API_KEY e plano/API com acesso a organizations/people search/enrichment; se a conta retornar API_INACCESSIBLE, o problema é permissão/plano do Apollo e não o botão do NODERE. Econodata exige ECONODATA_API_KEY e ECONODATA_API_URL oficial do contrato. LinkedIn pode vir do site do cliente, Apollo ou Econodata; quando não houver link confirmado, o sistema abre uma busca assistida por empresa, cidade e domínio para você validar manualmente."],
  ["13. Integrações", "A tela Integrações mostra status real de Google Places, Maps, PageSpeed, OpenAI, Supabase, WhatsApp, Econodata e Apollo. Chaves ficam no backend/Render ou no modo Admin; nunca no frontend público."],
  ["14. Tema, fonte e layout", "Em Configurações você altera tema, cor principal, modo claro/escuro, fonte, densidade e visual. Há temas escuros, claros, alto contraste e variações comerciais com cores fortes. A preferência é aplicada globalmente e salva neste navegador."],
  ["15. App no celular", "O menu inferior é rolável para mostrar as funções principais: Início, Busca, Empresas, CRM, IA, Inbox, Relatórios, Integrações, Configurações, Manual e Admin. A agenda de follow-up aparece dentro da ficha do lead/CRM."],
  ["16. Login, sessão e usuários", "O acesso ao sistema é protegido. Sem sessão válida, o usuário vê apenas a tela de login, cadastro, termos ou privacidade. Após login, a sessão fica em cookie httpOnly e o cabeçalho mostra email e workspace reais. O botão Sair encerra a sessão."],
  ["17. Busca avançada", "A busca possui três modos: Google Places local, CNPJ direto e Global/Internacional. Google Places usa backend seguro e filtra empresas já salvas. CNPJ direto consulta ReceitaWS e retorna uma empresa pronta para salvar. A busca internacional usa país/região quando informado."],
  ["18. Resultado de busca limpo", "Ao iniciar uma nova busca, resultados anteriores não salvos são apagados imediatamente. Apenas leads salvos no CRM permanecem na base, evitando mistura entre pesquisas diferentes."],
  ["19. LinkedIn", "Links do LinkedIn usam somente o nome da empresa. O sistema remove domínio, protocolo e complementos antes de montar a busca, evitando consultas como empresa.com."],
  ["20. Telefone e WhatsApp", "Telefones fixos brasileiros ficam em telefone principal e não aparecem no botão WhatsApp. O WhatsApp só é preenchido automaticamente quando o número tem DDD + celular com 9 dígitos iniciado por 9."],
  ["21. Decisores", "A API permite cadastrar, editar, listar e excluir decisores por empresa. Cada decisor tem nome, cargo, email, telefone, WhatsApp, LinkedIn e observações. O cadastro fica vinculado ao workspace e à empresa."],
  ["22. Calendário", "A página Calendário permite criar eventos reais com tipo, prioridade, data inicial, data final e notas. Os eventos são salvos em Supabase pela rota /api/calendar. Integrações Google Calendar e Outlook ficam preparadas por variáveis de ambiente futuras."],
  ["23. Catálogo", "A página Catálogo permite criar produtos e serviços com código automático, categoria, preço, custo, escopo, entregáveis e SLA. O catálogo usa /api/catalog e os itens podem ser vinculados ao cliente pela rota de contratos."],
  ["24. Comunicações", "A ficha da empresa pode registrar comunicações de WhatsApp, email, ligação, reunião, LinkedIn, Instagram, nota e interno. O histórico fica cronológico e vinculado ao cliente. Se SMTP_HOST, SMTP_USER, SMTP_PASS e SMTP_FROM estiverem configurados no Render, a ficha também envia e-mail real e salva o envio no histórico. Sem SMTP, o sistema mostra pendência clara e não finge envio."],
  ["25. Termos e privacidade", "As páginas /terms e /privacy ficam acessíveis sem login e documentam uso, armazenamento, isolamento por workspace e direitos LGPD. Elas também aparecem no rodapé do login e do app."],
  ["26. Importação CSV/XLSX", "Na aba Busca de empresas, use Importar empresas para enviar arquivo CSV ou XLSX, mapear colunas e importar em massa. O backend valida email, normaliza CNPJ/telefone, evita duplicidade por CNPJ ou nome+cidade, grava no Supabase e registra a importação em download_logs quando o banco está disponível. O modelo CSV fica em /api/companies/import/template."],
  ["27. Relatórios com gráficos", "A página Relatórios usa dados reais dos endpoints /api/reports/summary, /funnel, /timeline, /segments, /cities, /origin e /intelligence. Você pode alternar período entre 7d, 30d, 90d e 12m, mudar agrupamento diário/semanal/mensal e exportar via impressão/PDF com identidade NODERE."],
  ["28. Usuários, permissões e auditoria", "Owner/Admin criam usuários no Administrador e podem consultar em Configurações os usuários ativos, logs de auditoria e downloads/exportações do workspace. Perfis disponíveis: Owner, Administrador, Operador e Visualizador. Visualizador é voltado para leitura e não deve receber permissões administrativas."],
  ["29. Marketing e redes sociais", "A página Marketing possui templates de mensagem, campanhas e status das integrações sociais. Instagram/Facebook usam Meta OAuth, LinkedIn usa LinkedIn OAuth e Google Meu Negócio usa OAuth do Google Business quando as variáveis existem. mLabs aparece como atalho operacional para https://app.mlabs.com.br, pois não há API pública oficial de terceiros."],
  ["30. PDFs e documentos", "Relatórios de empresas, propostas e contratos gerados pelo navegador usam documento branco, texto escuro, cabeçalho NODERE e rodapé. A aparência do PDF é independente do tema claro/escuro da interface."],
  ["31. Erros comuns", "insufficient_quota indica falta de crédito OpenAI. not_configured indica variável ausente no Render. 401 indica rota protegida ou token. API_INACCESSIBLE no Apollo indica plano sem API habilitada. Busca vazia pode indicar limite da API, restrição de chave ou termo muito específico."]
];

export default function ManualPage() {
  return <ManualClient sections={sections} />;
}
