export const PREDEFINED_SEGMENTS = [
  "Advocacia",
  "Agropecuária",
  "Arquitetura e Urbanismo",
  "Bancos e Financeiras",
  "Beleza e Estética",
  "Blogs e Sites Pessoais",
  "Clínicas e Saúde",
  "Comércio Varejista",
  "Concessionárias de Veículos",
  "Construção Civil",
  "Contabilidade",
  "Demolição e Terraplanagem",
  "Distribuidoras e Atacadistas",
  "E-commerce",
  "Educação e Ensino",
  "Engenharia",
  "Esportes e Fitness",
  "Esoterismo",
  "Eventos e Entretenimento",
  "Farmácias e Drogarias",
  "Fotografia",
  "Gráfica e Impressão",
  "Hotéis e Hospedagem",
  "Imobiliárias e Corretores",
  "Indústria",
  "Instituições Religiosas",
  "Joalheria e Óticas",
  "Logística e Transportes",
  "Mecânica e Funilaria",
  "Músicos e Bandas",
  "Nutrição e Alimentação",
  "Pessoa Física e Profissional Liberal",
  "Pet Shop e Veterinária",
  "Poder Público e Governo",
  "Publicidade e Marketing",
  "Restaurantes e Alimentação",
  "Seguros",
  "Serviços Gerais",
  "Shoppings e Feiras Comerciais",
  "Sindicato Patronal",
  "Tecnologia e TI",
  "Telecomunicações",
  "Terceiro Setor e ONGs",
  "Turismo e Viagens",
  "Outros"
];
